version: '3.9'
services:

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sanity
      POSTGRES_PASSWORD: sanity
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
volumes:
  postgres.data: { }